### ISSUE TITLE
Create flask login

### ISSUE THREAD

**Issue by Aschwins** [Aschwins/webapp_amazons#6]
Create flask login where people can create their own username and password.

**Comment by Kunal614** [comment]
can i work on this ?

**Comment by Aschwins** [comment]
Feel free to fork and create a pull request, lad. Please rebase before asking to merge.

**Comment by Kunal614** [comment]
ok , but first can you please tell me , only i have to create login form with flask and no need to authentication or data storage  ?

**Comment by Aschwins** [comment]
Yea I suppose we need to have some data storage aswell. I will set up a data model with SQLAlchemy. Was thinking about using https://flask-login.readthedocs.io/en/latest/ for login management

**Comment by Kunal614** [comment]
ok i will use   firebase realtime database as a database
or any authentication setup also needed?

**Comment by Aschwins** [comment]
Kunal, thanks for offering your help! But I already implemented a first data model, and login/register/dashboard functionality with Flask Login, and pushed to master. For now we'll just use SQLite. So this issue is closed. There is still a lot of stuff to do around logging in tho, if you would still want to contribute.

Connecting users to the socket: #15 
Creating Anonymous functionality: #16
